export const SET_YEAR = 'SET_YEAR'
export const SET_PLAYING = 'TOGGLE_PLAYING'
export const INCREMENT_YEAR = 'INCREMENT_YEAR'

export const LOADING_SA3S = 'LOADING_SA3S'
export const LOADED_SA3S = 'LOADED_SA3S'

export const TOGGLE_DATASET = 'TOGGLE_DATASET'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_TAB = 'SET_TAB'

export const SET_WORDCLOUD_YEAR = 'SET_WORDCLOUD_YEAR'
export const SET_WORDCLOUD_TYPE = 'SET_WORDCLOUD_TYPE'