export const SET_YEAR = 'SET_YEAR'
export const SET_PLAYING = 'TOGGLE_PLAYING'
export const INCREMENT_YEAR = 'INCREMENT_YEAR'

export const LOADING_SA3S = 'LOADING_SA3S'
export const LOADED_SA3S = 'LOADED_SA3S'

export const LOADING_POINTS = 'LOADING_POINTS'
export const LOADED_POINTS = 'LOADED_POINTS'

export const TOGGLE_DATASET = 'TOGGLE_DATASET'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
